TEMPLATES = [
    {
        "id": "saas",
        "icon": "cloud",
        "name": {"id": "SaaS", "en": "SaaS"},
        "tagline": {"id": "Aplikasi berlangganan B2B/B2C dengan dashboard & billing", "en": "B2B/B2C subscription app with dashboard & billing"},
        "prefill": {
            "id": {
                "product_type": "SaaS (Software as a Service)",
                "target_users": "Tim bisnis kecil-menengah, startup, dan profesional yang butuh tool produktivitas berlangganan",
                "business_goal": "Monetisasi lewat subscription bulanan/tahunan (Free, Pro, Enterprise) dengan target MRR yang tumbuh stabil",
                "main_problem": "Proses kerja manual yang lambat dan tersebar di banyak tool tanpa satu sumber data terpusat",
                "desired_features": "Autentikasi & manajemen tim, dashboard analitik, manajemen data inti (CRUD), notifikasi, billing & subscription, pengaturan workspace, role & permission, onboarding wizard",
                "preferred_technology": "React + Tailwind di frontend, REST API di backend, PostgreSQL/MongoDB, deployment cloud",
                "design_preference": "Modern, minimal, profesional — nuansa SaaS premium dengan whitespace lega",
                "auth_requirement": "Email/password + Google OAuth, verifikasi email, reset password, role USER & ADMIN",
                "payment_requirement": "Subscription bulanan/tahunan via payment gateway (Stripe/Midtrans), free trial 14 hari",
                "integrations": "Email transaksional, analytics, penyimpanan file cloud",
                "deployment_preference": "Cloud (Vercel/AWS) dengan CI/CD",
                "additional_requirements": "Multi-tenant, responsive, SEO untuk landing page, audit log",
            },
            "en": {
                "product_type": "SaaS (Software as a Service)",
                "target_users": "SMB teams, startups, and professionals needing a subscription productivity tool",
                "business_goal": "Monetize via monthly/annual subscriptions (Free, Pro, Enterprise) with steadily growing MRR",
                "main_problem": "Slow manual workflows scattered across many tools with no single source of truth",
                "desired_features": "Auth & team management, analytics dashboard, core data CRUD, notifications, billing & subscriptions, workspace settings, roles & permissions, onboarding wizard",
                "preferred_technology": "React + Tailwind frontend, REST API backend, PostgreSQL/MongoDB, cloud deployment",
                "design_preference": "Modern, minimal, professional — premium SaaS feel with generous whitespace",
                "auth_requirement": "Email/password + Google OAuth, email verification, password reset, USER & ADMIN roles",
                "payment_requirement": "Monthly/annual subscription via payment gateway (Stripe), 14-day free trial",
                "integrations": "Transactional email, analytics, cloud file storage",
                "deployment_preference": "Cloud (Vercel/AWS) with CI/CD",
                "additional_requirements": "Multi-tenant, responsive, SEO for landing page, audit log",
            },
        },
    },
    {
        "id": "marketplace",
        "icon": "store",
        "name": {"id": "Marketplace", "en": "Marketplace"},
        "tagline": {"id": "Platform dua sisi: penjual & pembeli dengan checkout", "en": "Two-sided platform: sellers & buyers with checkout"},
        "prefill": {
            "id": {
                "product_type": "Marketplace multi-vendor",
                "target_users": "Penjual (UMKM/kreator) yang ingin membuka toko online dan pembeli yang mencari produk terkurasi",
                "business_goal": "Monetisasi lewat komisi transaksi per penjualan dan fitur promosi berbayar untuk penjual",
                "main_problem": "Penjual kesulitan menjangkau pembeli dan mengelola pesanan; pembeli sulit menemukan produk terpercaya di satu tempat",
                "desired_features": "Registrasi penjual & toko, katalog produk dengan pencarian & filter, keranjang & checkout, pembayaran online, manajemen pesanan, rating & review, dashboard penjual, dashboard admin untuk moderasi",
                "preferred_technology": "React di frontend, REST API di backend, PostgreSQL, object storage untuk gambar produk",
                "design_preference": "Bersih dan fokus pada produk, grid katalog, foto besar, trust signals",
                "auth_requirement": "Email/password + Google OAuth, role BUYER, SELLER, ADMIN",
                "payment_requirement": "Payment gateway (Midtrans/Stripe) dengan escrow/split payment ke penjual, QRIS",
                "integrations": "Email notifikasi pesanan, penyimpanan gambar, kurir/ongkir jika produk fisik",
                "deployment_preference": "Cloud dengan autoscaling",
                "additional_requirements": "Pencarian cepat, pagination, keamanan transaksi, laporan penjualan",
            },
            "en": {
                "product_type": "Multi-vendor marketplace",
                "target_users": "Sellers (SMBs/creators) wanting an online storefront and buyers looking for curated products",
                "business_goal": "Monetize via per-sale transaction fees and paid promotion features for sellers",
                "main_problem": "Sellers struggle to reach buyers and manage orders; buyers can't find trusted products in one place",
                "desired_features": "Seller & store registration, product catalog with search & filters, cart & checkout, online payments, order management, ratings & reviews, seller dashboard, admin moderation dashboard",
                "preferred_technology": "React frontend, REST API backend, PostgreSQL, object storage for product images",
                "design_preference": "Clean and product-focused, catalog grid, large photos, trust signals",
                "auth_requirement": "Email/password + Google OAuth, BUYER, SELLER, ADMIN roles",
                "payment_requirement": "Payment gateway (Stripe) with escrow/split payment to sellers",
                "integrations": "Order email notifications, image storage, shipping rates if physical goods",
                "deployment_preference": "Cloud with autoscaling",
                "additional_requirements": "Fast search, pagination, transaction security, sales reports",
            },
        },
    },
    {
        "id": "mobile-app",
        "icon": "smartphone",
        "name": {"id": "Mobile App", "en": "Mobile App"},
        "tagline": {"id": "Aplikasi mobile dengan backend API & push notification", "en": "Mobile app with backend API & push notifications"},
        "prefill": {
            "id": {
                "product_type": "Aplikasi mobile (iOS & Android)",
                "target_users": "Pengguna mobile-first yang mengakses layanan on-the-go setiap hari",
                "business_goal": "Membangun daily active users tinggi dengan retensi kuat, monetisasi lewat freemium/in-app purchase",
                "main_problem": "Kebutuhan pengguna belum terlayani dalam format mobile yang cepat, ringan, dan bisa dipakai kapan saja",
                "desired_features": "Onboarding, autentikasi, home feed, fitur inti aplikasi, profil pengguna, push notification, mode offline dasar, pengaturan",
                "preferred_technology": "React Native/Flutter untuk mobile, REST API backend, PostgreSQL/MongoDB",
                "design_preference": "Mobile-first, gesture friendly, bottom navigation, dark mode support",
                "auth_requirement": "Login sosial (Google/Apple) + email, biometrik opsional, token-based session",
                "payment_requirement": "In-app purchase / subscription melalui App Store & Play Store jika relevan",
                "integrations": "Push notification (FCM/APNs), analytics, crash reporting",
                "deployment_preference": "Backend di cloud; distribusi via App Store & Google Play",
                "additional_requirements": "Performa cepat (<2s load), offline-first untuk data penting, deep linking",
            },
            "en": {
                "product_type": "Mobile app (iOS & Android)",
                "target_users": "Mobile-first users accessing the service on the go every day",
                "business_goal": "Build high daily active users with strong retention, monetize via freemium/in-app purchases",
                "main_problem": "User needs are not served in a fast, lightweight mobile format usable anywhere",
                "desired_features": "Onboarding, authentication, home feed, core app features, user profile, push notifications, basic offline mode, settings",
                "preferred_technology": "React Native/Flutter for mobile, REST API backend, PostgreSQL/MongoDB",
                "design_preference": "Mobile-first, gesture friendly, bottom navigation, dark mode support",
                "auth_requirement": "Social login (Google/Apple) + email, optional biometrics, token-based sessions",
                "payment_requirement": "In-app purchases / subscriptions via App Store & Play Store if relevant",
                "integrations": "Push notifications (FCM/APNs), analytics, crash reporting",
                "deployment_preference": "Backend on cloud; distribution via App Store & Google Play",
                "additional_requirements": "Fast performance (<2s load), offline-first for key data, deep linking",
            },
        },
    },
    {
        "id": "ecommerce",
        "icon": "shopping-cart",
        "name": {"id": "E-Commerce", "en": "E-Commerce"},
        "tagline": {"id": "Toko online single-brand dengan katalog & pembayaran", "en": "Single-brand online store with catalog & payments"},
        "prefill": {
            "id": {
                "product_type": "E-Commerce (toko online single brand)",
                "target_users": "Pelanggan retail yang berbelanja produk brand secara online",
                "business_goal": "Meningkatkan penjualan langsung (D2C) tanpa ketergantungan marketplace pihak ketiga",
                "main_problem": "Brand kehilangan margin dan data pelanggan saat hanya berjualan lewat marketplace pihak ketiga",
                "desired_features": "Katalog produk & varian, pencarian & filter, keranjang, checkout & pembayaran, manajemen stok, kupon/diskon, tracking pesanan, halaman CMS (about, FAQ), dashboard admin",
                "preferred_technology": "React/Next.js untuk SEO, REST API, PostgreSQL",
                "design_preference": "Visual brand kuat, foto produk besar, konversi-oriented, mobile-first",
                "auth_requirement": "Guest checkout + akun opsional dengan email/Google",
                "payment_requirement": "Payment gateway lengkap (kartu, VA, e-wallet, QRIS), refund flow",
                "integrations": "Kurir & ongkir otomatis, email/WhatsApp notifikasi, analytics e-commerce",
                "deployment_preference": "Cloud dengan CDN untuk aset gambar",
                "additional_requirements": "SEO kuat, kecepatan halaman, schema.org product markup",
            },
            "en": {
                "product_type": "E-Commerce (single-brand online store)",
                "target_users": "Retail customers shopping the brand's products online",
                "business_goal": "Grow direct-to-consumer sales without third-party marketplace dependency",
                "main_problem": "The brand loses margin and customer data when selling only through third-party marketplaces",
                "desired_features": "Product catalog & variants, search & filters, cart, checkout & payments, inventory management, coupons/discounts, order tracking, CMS pages (about, FAQ), admin dashboard",
                "preferred_technology": "React/Next.js for SEO, REST API, PostgreSQL",
                "design_preference": "Strong brand visuals, large product photos, conversion-oriented, mobile-first",
                "auth_requirement": "Guest checkout + optional account with email/Google",
                "payment_requirement": "Full payment gateway (cards, wallets), refund flow",
                "integrations": "Shipping rates & tracking, email notifications, e-commerce analytics",
                "deployment_preference": "Cloud with CDN for image assets",
                "additional_requirements": "Strong SEO, page speed, schema.org product markup",
            },
        },
    },
    {
        "id": "ai-saas",
        "icon": "sparkles",
        "name": {"id": "AI SaaS", "en": "AI SaaS"},
        "tagline": {"id": "Produk AI dengan generation workflow & usage tracking", "en": "AI product with generation workflows & usage tracking"},
        "prefill": {
            "id": {
                "product_type": "AI SaaS",
                "target_users": "Profesional dan tim yang ingin mengotomasi pekerjaan konten/analisis dengan AI",
                "business_goal": "Monetisasi berbasis usage/credits dan subscription tier dengan cost control ketat terhadap biaya API LLM",
                "main_problem": "Pekerjaan repetitif berbasis teks/analisis memakan waktu dan hasilnya tidak konsisten tanpa bantuan AI",
                "desired_features": "Input requirement/prompt user, AI generation dengan streaming/progress, riwayat & versioning hasil, edit hasil, export, usage & token tracking, limit per plan, template prompt",
                "preferred_technology": "React frontend, FastAPI/Node backend, integrasi LLM provider (abstraction layer agar provider bisa diganti), MongoDB/PostgreSQL",
                "design_preference": "AI SaaS modern, dark mode premium, fokus pada area hasil generasi",
                "auth_requirement": "Email/Google OAuth, role USER & ADMIN",
                "payment_requirement": "Subscription + credits top-up, arsitektur siap payment gateway",
                "integrations": "LLM API (OpenAI/Anthropic/Gemini) via abstraction, email, analytics",
                "deployment_preference": "Cloud, environment variable untuk API key, tidak pernah expose key di frontend",
                "additional_requirements": "Validasi output AI, retry & fallback saat generasi gagal, rate limiting, logging generasi",
            },
            "en": {
                "product_type": "AI SaaS",
                "target_users": "Professionals and teams automating content/analysis work with AI",
                "business_goal": "Usage/credit-based monetization plus subscription tiers with strict LLM API cost control",
                "main_problem": "Repetitive text/analysis work is slow and inconsistent without AI assistance",
                "desired_features": "User requirement/prompt input, AI generation with streaming/progress, result history & versioning, result editing, export, usage & token tracking, per-plan limits, prompt templates",
                "preferred_technology": "React frontend, FastAPI/Node backend, LLM provider integration (abstraction layer for swappable providers), MongoDB/PostgreSQL",
                "design_preference": "Modern AI SaaS, premium dark mode, focus on the generation output area",
                "auth_requirement": "Email/Google OAuth, USER & ADMIN roles",
                "payment_requirement": "Subscription + credit top-ups, payment-gateway-ready architecture",
                "integrations": "LLM APIs (OpenAI/Anthropic/Gemini) via abstraction, email, analytics",
                "deployment_preference": "Cloud, API keys in env variables, never exposed to frontend",
                "additional_requirements": "AI output validation, retry & fallback on failed generations, rate limiting, generation logging",
            },
        },
    },
    {
        "id": "internal-tool",
        "icon": "wrench",
        "name": {"id": "Internal Tool", "en": "Internal Tool"},
        "tagline": {"id": "Tool operasional internal: data, approval, laporan", "en": "Internal ops tool: data, approvals, reports"},
        "prefill": {
            "id": {
                "product_type": "Internal tool / back-office",
                "target_users": "Tim internal perusahaan (operasional, finance, HR) dengan role berbeda",
                "business_goal": "Efisiensi operasional: memangkas proses manual berbasis spreadsheet dan email",
                "main_problem": "Data operasional tersebar di spreadsheet, approval lewat chat, tidak ada audit trail",
                "desired_features": "CRUD data inti dengan tabel & filter, workflow approval multi-level, import/export CSV, laporan & grafik, manajemen user & role, audit log, notifikasi",
                "preferred_technology": "React + component library, REST API, PostgreSQL",
                "design_preference": "Fungsional dan padat informasi, tabel data kuat, form efisien",
                "auth_requirement": "SSO perusahaan / Google Workspace, role-based access control granular",
                "payment_requirement": "Tidak perlu payment",
                "integrations": "Email/Slack notifikasi, export ke spreadsheet",
                "deployment_preference": "Private cloud / VPS internal, akses via VPN jika perlu",
                "additional_requirements": "Audit trail lengkap, backup data, permission per modul",
            },
            "en": {
                "product_type": "Internal tool / back-office",
                "target_users": "Internal company teams (ops, finance, HR) with different roles",
                "business_goal": "Operational efficiency: cut manual spreadsheet-and-email processes",
                "main_problem": "Operational data lives in spreadsheets, approvals happen in chat, no audit trail",
                "desired_features": "Core data CRUD with tables & filters, multi-level approval workflow, CSV import/export, reports & charts, user & role management, audit log, notifications",
                "preferred_technology": "React + component library, REST API, PostgreSQL",
                "design_preference": "Functional and information-dense, strong data tables, efficient forms",
                "auth_requirement": "Company SSO / Google Workspace, granular role-based access control",
                "payment_requirement": "No payments needed",
                "integrations": "Email/Slack notifications, spreadsheet export",
                "deployment_preference": "Private cloud / internal VPS, VPN access if needed",
                "additional_requirements": "Full audit trail, data backups, per-module permissions",
            },
        },
    },
]
