import { motion } from "framer-motion";
import { useLang } from "../../context/LanguageContext";
import { Lightbulb, FileText, Bot, Monitor, Server, Plug } from "lucide-react";

const t = {
  id: {
    label: "WORKFLOW",
    title: "Satu alur. Tidak ada yang dilompati.",
    sub: "Setiap prompt AI Agent yang dihasilkan PRD CreativeAI memaksa urutan kerja yang benar.",
    steps: [
      { id: "idea", icon: Lightbulb, h: "Idea", p: "Ide produk Anda" },
      { id: "prd", icon: FileText, h: "PRD", p: "Dokumen inti implementasi" },
      { id: "prompt", icon: Bot, h: "Agent Prompt", p: "Prompt implementasi" },
      { id: "frontend", icon: Monitor, h: "Frontend", p: "Phase 1 — UI dulu" },
      { id: "backend", icon: Server, h: "Backend", p: "Phase 2 — API & DB" },
      { id: "integration", icon: Plug, h: "Integration", p: "Phase 3 — E2E" },
    ],
  },
  en: {
    label: "WORKFLOW",
    title: "One flow. Nothing gets skipped.",
    sub: "Every AI Agent prompt generated by PRD CreativeAI enforces the correct order of work.",
    steps: [
      { id: "idea", icon: Lightbulb, h: "Idea", p: "Your product idea" },
      { id: "prd", icon: FileText, h: "PRD", p: "Core implementation document" },
      { id: "prompt", icon: Bot, h: "Agent Prompt", p: "Implementation prompt" },
      { id: "frontend", icon: Monitor, h: "Frontend", p: "Phase 1 — UI first" },
      { id: "backend", icon: Server, h: "Backend", p: "Phase 2 — API & DB" },
      { id: "integration", icon: Plug, h: "Integration", p: "Phase 3 — E2E" },
    ],
  },
};

export default function Workflow() {
  const { lang } = useLang();
  const c = t[lang];
  return (
    <section className="border-y border-white/10 bg-[#0D0D0F] py-28" data-testid="workflow-section">
      <div className="max-w-7xl mx-auto px-6 lg:px-10">
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6 }}>
          <p className="text-xs font-mono tracking-[0.3em] text-indigo-400 mb-4">{c.label}</p>
          <h2 className="font-display text-3xl md:text-5xl font-bold tracking-tight">{c.title}</h2>
          <p className="mt-4 text-zinc-400 max-w-xl">{c.sub}</p>
        </motion.div>
        <div className="mt-16 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
          {c.steps.map((s, i) => (
            <motion.div key={s.id} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-40px" }} transition={{ duration: 0.5, delay: i * 0.1 }}
              className="relative bg-[#121212] border border-white/10 rounded-2xl p-6 card-hover">
              <span className="absolute top-4 right-4 font-mono text-[10px] text-zinc-600">{String(i + 1).padStart(2, "0")}</span>
              <div className={`w-10 h-10 rounded-lg flex items-center justify-center mb-5 ${i >= 3 ? "bg-emerald-500/10 border border-emerald-500/20" : "bg-indigo-500/10 border border-indigo-500/20"}`}>
                <s.icon size={18} className={i >= 3 ? "text-emerald-400" : "text-indigo-400"} />
              </div>
              <h3 className="font-display font-bold text-sm">{s.h}</h3>
              <p className="text-zinc-500 text-xs mt-1.5">{s.p}</p>
              {i < 5 && <span className="hidden lg:block absolute -right-3.5 top-1/2 -translate-y-1/2 text-zinc-600 z-10">→</span>}
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
